# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VectoeFDX_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_localip = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_localip.setGeometry(QtCore.QRect(70, 50, 113, 20))
        self.lineEdit_localip.setObjectName("lineEdit_localip")
        self.label_localip = QtWidgets.QLabel(self.centralwidget)
        self.label_localip.setGeometry(QtCore.QRect(10, 50, 47, 13))
        self.label_localip.setObjectName("label_localip")
        self.label_localport = QtWidgets.QLabel(self.centralwidget)
        self.label_localport.setGeometry(QtCore.QRect(230, 50, 47, 13))
        self.label_localport.setObjectName("label_localport")
        self.lineEdit_localport = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_localport.setGeometry(QtCore.QRect(290, 50, 113, 20))
        self.lineEdit_localport.setObjectName("lineEdit_localport")
        self.label_targetip = QtWidgets.QLabel(self.centralwidget)
        self.label_targetip.setGeometry(QtCore.QRect(10, 90, 47, 13))
        self.label_targetip.setObjectName("label_targetip")
        self.lineEdit_targetip = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_targetip.setGeometry(QtCore.QRect(70, 90, 113, 20))
        self.lineEdit_targetip.setObjectName("lineEdit_targetip")
        self.label_targetport = QtWidgets.QLabel(self.centralwidget)
        self.label_targetport.setGeometry(QtCore.QRect(230, 90, 61, 16))
        self.label_targetport.setObjectName("label_targetport")
        self.lineEdit_targetport = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_targetport.setGeometry(QtCore.QRect(290, 90, 113, 20))
        self.lineEdit_targetport.setObjectName("lineEdit_targetport")
        self.pushButton_fdxConnect = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_fdxConnect.setGeometry(QtCore.QRect(480, 50, 75, 23))
        self.pushButton_fdxConnect.setObjectName("pushButton_fdxConnect")
        self.textBrowser_info = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_info.setGeometry(QtCore.QRect(10, 340, 551, 221))
        self.textBrowser_info.setObjectName("textBrowser_info")
        self.pushButton_StartCANoe = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_StartCANoe.setGeometry(QtCore.QRect(50, 170, 75, 23))
        self.pushButton_StartCANoe.setObjectName("pushButton_StartCANoe")
        self.pushButton_StopCANoe = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_StopCANoe.setGeometry(QtCore.QRect(210, 170, 75, 23))
        self.pushButton_StopCANoe.setObjectName("pushButton_StopCANoe")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit_localip.setText(_translate("MainWindow", "127.0.0.1"))
        self.label_localip.setText(_translate("MainWindow", "local_ip"))
        self.label_localport.setText(_translate("MainWindow", "local_port"))
        self.lineEdit_localport.setText(_translate("MainWindow", "2000"))
        self.label_targetip.setText(_translate("MainWindow", "target_ip"))
        self.lineEdit_targetip.setText(_translate("MainWindow", "127.0.0.1"))
        self.label_targetport.setText(_translate("MainWindow", "target_port"))
        self.lineEdit_targetport.setText(_translate("MainWindow", "2001"))
        self.pushButton_fdxConnect.setText(_translate("MainWindow", "Connect"))
        self.pushButton_StartCANoe.setText(_translate("MainWindow", "StartCANoe"))
        self.pushButton_StopCANoe.setText(_translate("MainWindow", "StopCANoe"))
